Feature/web 436/autocomplete improvement
TFG-Labs/custom-shipping-step-by-items pull request #109
Opened 2024-07-26 10:31 UTC by NosiphoManyase

### What problem is this solving?
This change is meant to encourage users to enter addresses using google autocomplete as well as . 

Desired change is not achieved exactly as required
Reason: You cannot access/manipulate returned google autocomplete addresses data until the users click on a suggested address (i.e through debouncing).

What has been achieved?

- **requests** for autocomplete addresses only executes **after 2 input value chars** are inserted by the user - this reduces requests
- if user backspaces to **less than 3 input chars**, google **autocomplete** and it's listener is **removed** to reduce requests as it stays mounted otherwise.
- To reduce premature error messaging for addresses  :
           1. A function **isSlowerNetwork** checks user network speed, if user is on slower network - **delay to error messages** is increased to 3s - from testing with throttled network this autocomplete response will not always be recieved in 3seconds.
           2. Before **checkAddressResults** function is **called** to evaluate if response has been received in order to display not found address message - I've put in logic to prevent checkAddressResults from executing if user is **still typing** **number**(house number) **or** has just put in a **space** in order to start typing street name. This will decrease premature address error message

### Used delay times stipulated in ticket for 'faster' networks and 3s for slow networks - behaviour looks like it needs longer delay times

#### How it works
Detailed above

#### How to test it?
- Test a few a few addresses and use checklist of what's been achieved above against current behaviour in prod.
- Test with fast and slow network.
- Check if code changes are efficient.

[Workspace](https://autocompleteweb436--thefoschini.myvtex.com/checkout/#/shipping)

### Screenshots/Video example usage:
- Desktop
- Tablet
- Movil

https://github.com/user-attachments/assets/9cc648ba-d5ba-4ee1-a545-5f86b2fee2eb

https://github.com/user-attachments/assets/62a9f9ee-78e7-4dcc-a0a7-0ba6681919c7

### Related to / Depends on

#### How does this PR make you feel? :link:
![]()

2024-07-30 07:57 UTC, simmbiote requested changes
@NosiphoManyase nice use of connection api!
I'm seeing a blank screen on the workspace at the moment. 
![image](https://github.com/user-attachments/assets/f96aedb2-e3bc-483b-ae34-281022f6dfd3)

2024-07-30 08:24 UTC, NosiphoManyase commented
> @NosiphoManyase nice use of connection api! I'm seeing a blank screen on the workspace at the moment. ![image](https://private-user-images.githubusercontent.com/11704483/353371627-f96aedb2-e3bc-483b-ae34-281022f6dfd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjc5OTQsIm5iZiI6MTcyMjMyNzY5NCwicGF0aCI6Ii8xMTcwNDQ4My8zNTMzNzE2MjctZjk2YWVkYjItZTNiYy00ODNiLWFlMzQtMjgxMDIyZjZkZmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA4MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYTUyOTdiMDdhNDdiNDlhMGVmZjFlYzMxZTMyODY5NDY2NjdjMDQzMGNlMjM0ZDk2YTg3OTQyNDhmMmZiMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JpMYyolbesagfvpC5MsQ4Y-L5UJWte3RUMgTfROEEWk)

@simmbiote, I think it's because I put a link directly to checkout it returns blank if you're not logged in yet. Go to landing page and just let me know if you win

2024-08-01 08:28 UTC, SegopotsoMakhutja commented on checkout-ui-custom/src/partials/Deliver/AddressForm.js
> +    <a
please pull the latest develop, these changes should not be there. i reverted this. @NosiphoManyase

2024-08-01 09:03 UTC, SegopotsoMakhutja commented on checkout-ui-custom/src/utils/translations.js
> +  $('.btn-go-to-shippping-method').text('Delete address');
this should also not be here.

2024-08-01 09:04 UTC, NosiphoManyase commented on checkout-ui-custom/src/utils/translations.js
> +  $('.btn-go-to-shippping-method').text('Delete address');
Thanks, let me pull latest changes

2024-08-01 09:49 UTC, SegopotsoMakhutja approved these changes

2024-09-08 18:03 UTC, closed without merging