[WEB-452] - Add delete address functionality
TFG-Labs/custom-shipping-step-by-items pull request #110
Opened 2024-07-29 07:28 UTC by SegopotsoMakhutja

### What problem is this solving?
- adding delete functionality to checkout

https://www.notion.so/bashdotcom/Address-Swarm-1-Adding-Delete-Functionality-for-addresses-in-Checkout-f8f94da2c6984c5298a6cba15fb043b1?pvs=4

https://www.figma.com/design/M9vAdnEoGENzSD3OkaE7BB/%5BWEB%5D-Cart-%26-Checkout?node-id=6448-311894&m=dev

#### How it works
[x] refactor checkout index db transactions
[x] remove address from checkout index DB
[x] remove address from orderForm shippingData
[x] remove address from masterData
[x] shows alert box

#### How to test it?

[Workspace](https://deleteaddress--thefoschini.myvtex.com/checkout/#/shipping)

### Screenshots/Video example usage:
![Screenshot 2024-07-29 at 09 25 13](https://github.com/user-attachments/assets/03326f91-a92d-45cf-86c4-dbb7e43cb791)

### Related to / Depends on

#### How does this PR make you feel? :link:
![]()

2024-07-30 08:04 UTC, simmbiote requested changes
Hi @SegopotsoMakhutja getting stuck here at the moment on the workspace
![image](https://github.com/user-attachments/assets/28857569-a4c3-4ef9-8bbf-740f3603e078)

2024-07-31 11:01 UTC, simmbiote requested changes

2024-07-31 11:01 UTC, simmbiote commented on checkout-ui-custom/src/utils/deleteAddress.js
> +      removeAddressFromMasterData(address.id),
@SegopotsoMakhutja I think we can do a try {} catch here.
No need to prevent the user from checking out if MasterData fails/

2024-08-01 07:55 UTC, simmbiote requested changes
Hey Sego, the address was deleted from indexedDb, but the list of addresses did not update

![image](https://github.com/user-attachments/assets/77cc934f-8e91-45f1-831c-13745811c528)

2024-08-01 07:58 UTC, simmbiote commented
@SegopotsoMakhutja this error from trying to delete from MD is interesting - maybe the ID is not being passed correctly?
![image](https://github.com/user-attachments/assets/568f2a15-3861-4b70-8233-c4abb6ae9e51)

2024-08-01 12:12 UTC, SegopotsoMakhutja commented
> @SegopotsoMakhutja this error from trying to delete from MD is interesting - maybe the ID is not being passed correctly?
> 
> ![image](https://github.com/user-attachments/assets/568f2a15-3861-4b70-8233-c4abb6ae9e51)
> 
> 

yip this is the first time i see this one, do you recall if the confirm pop up showed the ID?

2024-08-01 13:42 UTC, simmbiote approved these changes
Nice 👍 🎸

2024-08-05 07:59 UTC, merged